### ISSUE TITLE
[Bug] There is no way to delete a clock card

### ISSUE THREAD

**Issue by serrq** [Bnyro/ClockYou#44]
I cannot delete any time zone card in clock tab.

**Comment by Bnyro** [comment]
You can the same way you enabled them.

**Comment by eclairevoyant** [comment]
@Bnyro This is still a bug as of version 3.1 (on Android 13) and is reliably reproducible.

Steps to reproduce:
1. Click pencil icon
1. Search for timezone (e.g. Melbourne)
1. Check box
     * Timezone gets added
1. Click pencil icon
1. Search for same timezone (e.g. Melbourne)
     * Box still appears unchecked (!) - bug 1
1. Check box
    * Timezone is removed, but app crashes - bug 2

Stacktrace:
```
FATAL EXCEPTION: DefaultDispatcher-worker-1
Process: com.bnyro.clock, PID: 31657
android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: timeZones.name (code 1555 SQLITE_CONSTRAINT_PRIMARYKEY)
	at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:961)
	at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:790)
	at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:89)
	at x3.g.P(Unknown Source:2)
	at f4.d$d.call(SourceFile:62)
	at s3.b.k(Unknown Source:5)
	at x5.a.m(Unknown Source:8)
	at m6.i0.run(Unknown Source:100)
	at q3.c.run(SourceFile:85)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: m6.g0: [p1{Cancelling}@ff6b66f, Dispatchers.IO]
```

I would also suggest pushing the already-checked timezones to the top so they can be easily unselected by the user instead of having to search.
